create table public.artists (
    id serial primary key,
    name text not null unique
);

create table public.genres (
    id serial primary key,
    code text not null unique,
    name text not null,
    last_updated timestamptz
);

create table public.songs (
    id serial primary key,
    title text not null,
    artist_id integer not null references public.artists(id) on delete cascade,
    album text,
    art text,
    melon_song_id bigint unique,
    youtube_url text,
    youtube_last_updated timestamptz,
    spotify_url text,
    apple_music_url text,
    apple_music_last_updated timestamptz,
    scraped_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (title, artist_id)
);

create table public.users (
    id uuid primary key,
    email text unique,
    spotify_access_token text,
    spotify_refresh_token text,
    spotify_expires_at bigint,
    is_spotify_connected boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.playlists (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(id) on delete cascade,
    name text not null,
    created_at timestamptz not null default now()
);

create table public.playlist_songs (
    playlist_id bigint not null references public.playlists(id) on delete cascade,
    song_id integer not null references public.songs(id) on delete cascade,
    position integer not null default 0,
    created_at timestamptz not null default now(),
    primary key (playlist_id, song_id)
);

create table public.song_rankings (
    song_id integer not null references public.songs(id) on delete cascade,
    genre_id integer not null references public.genres(id) on delete cascade,
    rank integer not null,
    movement text,
    scraped_at timestamptz not null default now(),
    primary key (song_id, genre_id)
);

create table public.song_lyrics (
    song_id integer primary key references public.songs(id) on delete cascade,
    lyrics text,
    eng_saved boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.cron_state (
    id integer primary key,
    last_genre_index integer not null default 0,
    updated_at timestamptz not null default now()
);

create table public.chart_refresh_state (
    genre_code text primary key references public.genres(code) on delete cascade,
    status text not null default 'idle',
    reason text,
    last_started_at timestamptz,
    last_finished_at timestamptz,
    last_success_at timestamptz,
    last_error text,
    updated_at timestamptz not null default now()
);

create index playlist_songs_playlist_position_idx
    on public.playlist_songs (playlist_id, position);

create index song_rankings_genre_rank_idx
    on public.song_rankings (genre_id, rank);

create index chart_refresh_state_status_idx
    on public.chart_refresh_state (status, updated_at desc);

alter table public.users enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_songs enable row level security;
alter table public.songs enable row level security;

create policy users_select_own
    on public.users
    for select
    to authenticated
    using (auth.uid() = id);

create policy users_update_own
    on public.users
    for update
    to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);

create policy playlists_select_own
    on public.playlists
    for select
    to authenticated
    using (auth.uid() = user_id);

create policy playlists_insert_own
    on public.playlists
    for insert
    to authenticated
    with check (auth.uid() = user_id);

create policy playlists_update_own
    on public.playlists
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy playlists_delete_own
    on public.playlists
    for delete
    to authenticated
    using (auth.uid() = user_id);

create policy playlist_songs_select_via_own_playlist
    on public.playlist_songs
    for select
    to authenticated
    using (
        exists (
            select 1
            from public.playlists
            where playlists.id = playlist_songs.playlist_id
              and playlists.user_id = auth.uid()
        )
    );

create policy playlist_songs_insert_via_own_playlist
    on public.playlist_songs
    for insert
    to authenticated
    with check (
        exists (
            select 1
            from public.playlists
            where playlists.id = playlist_songs.playlist_id
              and playlists.user_id = auth.uid()
        )
    );

create policy playlist_songs_update_via_own_playlist
    on public.playlist_songs
    for update
    to authenticated
    using (
        exists (
            select 1
            from public.playlists
            where playlists.id = playlist_songs.playlist_id
              and playlists.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1
            from public.playlists
            where playlists.id = playlist_songs.playlist_id
              and playlists.user_id = auth.uid()
        )
    );

create policy playlist_songs_delete_via_own_playlist
    on public.playlist_songs
    for delete
    to authenticated
    using (
        exists (
            select 1
            from public.playlists
            where playlists.id = playlist_songs.playlist_id
              and playlists.user_id = auth.uid()
        )
    );

create policy songs_select_authenticated
    on public.songs
    for select
    to authenticated
    using (true);
